import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex h-screen'>
          <div className='bg-[#121212] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
