import SideBar from '../cmps/side-bar/side-bar'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex h-screen'>
          <SideBar />
          <div className='bg-[#121212] flex-1 overflow-y-scroll'>{children}</div>
        </div>
      </body>
    </html>
  )
}
